export const HARD_SKILLS = [
  { label: "Java", aliases: ["java", "jvm"] },
  { label: "Spring Boot", aliases: ["spring boot", "springboot", "spring cloud"] },
  { label: "Go", aliases: ["golang", " go "] },
  { label: "C++", aliases: ["c++", "cpp"] },
  { label: "Python", aliases: ["python", "py"] },
  { label: "JavaScript", aliases: ["javascript", "js", "ecmascript"] },
  { label: "TypeScript", aliases: ["typescript", "ts"] },
  { label: "React", aliases: ["react", "react.js", "reactjs"] },
  { label: "Vue", aliases: ["vue", "vue.js", "vue3"] },
  { label: "Node.js", aliases: ["node.js", "nodejs", "node "] },
  { label: "Android", aliases: ["android"] },
  { label: "Kotlin", aliases: ["kotlin"] },
  { label: "移动端", aliases: ["移动端", "客户端", "ios", "android"] },
  { label: "MySQL", aliases: ["mysql"] },
  { label: "PostgreSQL", aliases: ["postgresql", "postgres"] },
  { label: "Redis", aliases: ["redis"] },
  { label: "MongoDB", aliases: ["mongodb", "mongo"] },
  { label: "Elasticsearch", aliases: ["elasticsearch", "elastic search", "es"] },
  { label: "Kafka", aliases: ["kafka"] },
  { label: "RabbitMQ", aliases: ["rabbitmq"] },
  { label: "Docker", aliases: ["docker", "容器"] },
  { label: "Kubernetes", aliases: ["kubernetes", "k8s"] },
  { label: "Linux", aliases: ["linux"] },
  { label: "Git", aliases: ["git"] },
  { label: "CI/CD", aliases: ["ci/cd", "cicd", "devops"] },
  { label: "性能优化", aliases: ["性能优化", "性能调优", "稳定性"] },
  { label: "微服务", aliases: ["微服务", "microservice", "microservices"] },
  { label: "分布式系统", aliases: ["分布式", "distributed"] },
  { label: "高并发", aliases: ["高并发", "并发", "concurrency"] },
  { label: "数据结构", aliases: ["数据结构", "data structure"] },
  { label: "算法", aliases: ["算法", "algorithm"] },
  { label: "机器学习", aliases: ["机器学习", "machine learning", "ml"] },
  { label: "深度学习", aliases: ["深度学习", "deep learning"] },
  { label: "计算机视觉", aliases: ["计算机视觉", "cv", "computer vision", "视觉算法"] },
  { label: "NLP", aliases: ["nlp", "自然语言处理"] },
  { label: "推荐系统", aliases: ["推荐系统", "recommendation"] },
  { label: "数据分析", aliases: ["数据分析", "data analysis"] },
  { label: "SQL", aliases: [" sql ", "hive sql"] },
  { label: "Excel", aliases: ["excel", "透视表", "vlookup"] },
  { label: "BI", aliases: ["bi", "tableau", "power bi", "帆软", "finebi", "看板"] },
  { label: "Hive", aliases: ["hive"] },
  { label: "Spark", aliases: ["spark", "pyspark"] },
  { label: "Flink", aliases: ["flink"] },
  { label: "A/B 测试", aliases: ["a/b", "ab test", "ab测试", "实验平台"] },
  { label: "用户增长", aliases: ["用户增长", "growth"] },
  { label: "产品设计", aliases: ["产品设计", "产品方案", "prd", "原型", "axure", "figma", "墨刀", "mockingbot"] },
  { label: "需求分析", aliases: ["需求分析", "需求调研", "需求拆解", "需求管理", "用户故事", "user story"] },
  { label: "用户研究", aliases: ["用户研究", "用户访谈", "问卷", "可用性测试", "用户洞察"] },
  { label: "竞品分析", aliases: ["竞品分析", "竞品调研", "市场分析"] },
  { label: "交互设计", aliases: ["交互设计", "信息架构", "流程图", "泳道图"] },
  { label: "产品规划", aliases: ["产品规划", "路线图", "roadmap", "版本规划"] },
  { label: "指标体系", aliases: ["指标体系", "北极星指标", "漏斗分析", "转化率", "留存"] },
  { label: "数据埋点", aliases: ["埋点", "数据埋点"] },
  { label: "增长策略", aliases: ["增长策略", "增长模型", "拉新", "促活", "留存", "转化"] },
  { label: "商业化", aliases: ["商业化", "变现", "定价", "收入模型"] },
  { label: "AI 产品", aliases: ["ai 产品", "AI产品", "大模型产品", "智能体", "llm", "大模型应用"] },
  { label: "数据产品", aliases: ["数据产品", "数据中台", "数据平台", "经营看板"] },
  { label: "供应链产品", aliases: ["供应链产品", "供应链", "履约", "库存", "采购"] },
  { label: "B端产品", aliases: ["b端", "b2b", "saas", "中后台", "后台产品", "平台产品"] },
  { label: "C端产品", aliases: ["c端", "b2c", "用户产品", "消费者产品"] },
  { label: "硬件产品", aliases: ["硬件产品", "智能硬件", "iot", "IoT"] },
  { label: "云计算", aliases: ["云计算", "云服务", "云平台", "cloud"] },
  { label: "游戏策划", aliases: ["游戏策划", "玩法设计", "关卡", "数值"] },
  { label: "内容生态", aliases: ["内容生态", "社区产品", "创作者", "内容消费"] },
  { label: "风控策略", aliases: ["风控", "风控策略", "风险策略", "反欺诈"] },
  { label: "IoT", aliases: ["iot", "物联网", "智能设备", "智能终端"] },
  { label: "智能驾驶", aliases: ["智能驾驶", "自动驾驶", "辅助驾驶", "adas"] },
  { label: "物流科技", aliases: ["物流科技", "物流", "仓配", "运力"] },
  { label: "PRD", aliases: ["prd", "需求文档", "产品需求文档"] },
  { label: "流程图", aliases: ["流程图", "泳道图", "业务流程"] },
  { label: "运营策略", aliases: ["运营策略", "活动运营", "内容运营"] },
  { label: "活动运营", aliases: ["活动运营", "活动策划", "活动复盘"] },
  { label: "内容运营", aliases: ["内容运营", "内容策划", "达人运营"] },
  { label: "项目管理", aliases: ["项目管理", "敏捷", "scrum", "jira", "禅道", "里程碑"] },
];

export const SOFT_SKILLS = [
  { label: "团队协作", aliases: ["团队协作", "协作", "跨团队", "cross-functional"] },
  { label: "沟通能力", aliases: ["沟通", "沟通能力", "表达"] },
  { label: "抗压能力", aliases: ["抗压", "压力", "高压"] },
  { label: " owner 意识", aliases: ["owner", "ownership", "主人翁"] },
  { label: "学习能力", aliases: ["学习能力", "快速学习", "自驱"] },
  { label: "问题分析", aliases: ["问题分析", "拆解问题", "分析能力"] },
  { label: "结果导向", aliases: ["结果导向", "目标导向", "闭环"] },
  { label: "业务理解", aliases: ["业务理解", "商业理解", "用户洞察"] },
  { label: "跨部门推动", aliases: ["跨部门", "资源协调", "推动", "项目推进", "stakeholder"] },
  { label: "用户洞察", aliases: ["用户洞察", "用户敏感度", "内容敏感度"] },
  { label: "逻辑思维", aliases: ["逻辑", "结构化", "逻辑思维"] },
];

export const ROLE_KEYWORDS = [
  "后端工程师",
  "前端工程师",
  "全栈工程师",
  "算法工程师",
  "数据分析师",
  "数据开发工程师",
  "产品经理",
  "增长产品经理",
  "平台产品经理",
  "数据产品经理",
  "商业产品经理",
  "B端产品经理",
  "C端产品经理",
  "运营",
  "测试工程师",
  "客户端工程师",
];

export const ROLE_FAMILIES = {
  product_manager: {
    label: "产品经理",
    categories: ["产品"],
    title_keywords: ["产品经理", "增长产品", "平台产品", "数据产品", "商业产品", "B端产品", "C端产品"],
    skills: [
      "产品设计",
      "需求分析",
      "用户研究",
      "竞品分析",
      "交互设计",
      "产品规划",
      "指标体系",
      "数据分析",
      "A/B 测试",
      "数据埋点",
      "SQL",
      "BI",
      "用户增长",
      "增长策略",
      "商业化",
      "B端产品",
      "C端产品",
      "项目管理",
    ],
  },
  technology: {
    label: "技术",
    categories: ["技术", "数据"],
    title_keywords: ["工程师", "开发", "算法", "数据分析师", "数据开发"],
    skills: ["Java", "Python", "Go", "C++", "React", "MySQL", "Redis", "Docker", "Kubernetes", "算法"],
  },
  operations: {
    label: "运营",
    categories: ["运营"],
    title_keywords: ["运营", "增长运营"],
    skills: ["用户增长", "运营策略", "数据分析", "A/B 测试", "增长策略"],
  },
};

export const CITY_KEYWORDS = [
  "北京",
  "上海",
  "深圳",
  "广州",
  "杭州",
  "成都",
  "武汉",
  "南京",
  "苏州",
  "西安",
  "厦门",
  "重庆",
];

export const DEGREE_RANK = {
  高中: 1,
  中专: 1,
  大专: 2,
  专科: 2,
  本科: 3,
  学士: 3,
  硕士: 4,
  研究生: 4,
  博士: 5,
};
